import { ModelTypeEnum, type ProviderConfigType } from '../../type';

// Exact IDs were reconciled with the Ace Data Cloud /openai/models response on 2026-10-09.
// Limits and capabilities follow the public model catalog and primary model documentation.
// Prices are omitted: FastGPT fields are instance points per 1,000 tokens, not Ace Credits.
const models: ProviderConfigType = {
  provider: 'AceDataCloud',
  list: [
    // OpenAI
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-6.1-sol',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-6-luna',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-6-sol',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-6-astra',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.6-luna',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.6-sol',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.6-sol-fast',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.6-terra',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.5',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.5-pro',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.4-mini',
      maxContext: 400000,
      maxTokens: 128000,
      quoteMaxToken: 272000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.4-nano',
      maxContext: 400000,
      maxTokens: 128000,
      quoteMaxToken: 272000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.4',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.4-pro',
      maxContext: 1050000,
      maxTokens: 128000,
      quoteMaxToken: 922000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.2',
      maxContext: 400000,
      maxTokens: 128000,
      quoteMaxToken: 272000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5.1',
      maxContext: 400000,
      maxTokens: 128000,
      quoteMaxToken: 272000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5-pro',
      maxContext: 400000,
      maxTokens: 272000,
      quoteMaxToken: 128000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5',
      maxContext: 400000,
      maxTokens: 128000,
      quoteMaxToken: 272000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5-mini',
      maxContext: 400000,
      maxTokens: 128000,
      quoteMaxToken: 272000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-5-nano',
      maxContext: 400000,
      maxTokens: 128000,
      quoteMaxToken: 272000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'o3-pro',
      maxContext: 200000,
      maxTokens: 100000,
      quoteMaxToken: 100000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'o3',
      maxContext: 200000,
      maxTokens: 100000,
      quoteMaxToken: 100000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'o4-mini',
      maxContext: 200000,
      maxTokens: 100000,
      quoteMaxToken: 100000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-4.1',
      maxContext: 1047576,
      maxTokens: 32768,
      quoteMaxToken: 1014808,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-4.1-mini',
      maxContext: 1047576,
      maxTokens: 32768,
      quoteMaxToken: 1014808,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-4.1-nano',
      maxContext: 1047576,
      maxTokens: 32768,
      quoteMaxToken: 1014808,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'o1-pro',
      maxContext: 200000,
      maxTokens: 100000,
      quoteMaxToken: 100000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'o3-mini',
      maxContext: 200000,
      maxTokens: 100000,
      quoteMaxToken: 100000,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'o1',
      maxContext: 200000,
      maxTokens: 100000,
      quoteMaxToken: 100000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'o1-mini',
      maxContext: 128000,
      maxTokens: 65536,
      quoteMaxToken: 62464,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: false,
      usedInToolCall: false,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-4o-mini',
      maxContext: 128000,
      maxTokens: 16384,
      quoteMaxToken: 111616,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-4o',
      maxContext: 128000,
      maxTokens: 16384,
      quoteMaxToken: 111616,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gpt-4',
      maxContext: 8192,
      maxTokens: 8192,
      quoteMaxToken: 6144,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    // Anthropic
    {
      type: ModelTypeEnum.llm,
      model: 'claude-fable-5-1',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 872000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-opus-5',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 872000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-sonnet-5',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 872000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-fable-5',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 872000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-opus-4-8',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 872000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-opus-4-7',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 872000,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-sonnet-4-6',
      maxContext: 1000000,
      maxTokens: 64000,
      quoteMaxToken: 936000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-opus-4-6',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 872000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-opus-4-5-20251101',
      maxContext: 200000,
      maxTokens: 64000,
      quoteMaxToken: 136000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-haiku-4-5-20251001',
      maxContext: 200000,
      maxTokens: 64000,
      quoteMaxToken: 136000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-sonnet-4-5-20250929',
      maxContext: 200000,
      maxTokens: 64000,
      quoteMaxToken: 136000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-opus-4-1-20250805',
      maxContext: 200000,
      maxTokens: 32000,
      quoteMaxToken: 168000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-opus-4-20250514',
      maxContext: 200000,
      maxTokens: 32000,
      quoteMaxToken: 168000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-sonnet-4-20250514',
      maxContext: 200000,
      maxTokens: 64000,
      quoteMaxToken: 136000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-3-7-sonnet-20250219',
      maxContext: 200000,
      maxTokens: 64000,
      quoteMaxToken: 136000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-3-5-haiku-20241022',
      maxContext: 200000,
      maxTokens: 8192,
      quoteMaxToken: 191808,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-3-5-sonnet-20241022',
      maxContext: 200000,
      maxTokens: 8192,
      quoteMaxToken: 191808,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-3-5-sonnet-20240620',
      maxContext: 200000,
      maxTokens: 8192,
      quoteMaxToken: 191808,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-3-haiku-20240307',
      maxContext: 200000,
      maxTokens: 4096,
      quoteMaxToken: 195904,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'claude-3-sonnet-20240229',
      maxContext: 200000,
      maxTokens: 4096,
      quoteMaxToken: 195904,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    // Google
    {
      type: ModelTypeEnum.llm,
      model: 'gemini-3.8-flash',
      maxContext: 1048576,
      maxTokens: 65536,
      quoteMaxToken: 983040,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gemini-3.7-flash',
      maxContext: 1048576,
      maxTokens: 65536,
      quoteMaxToken: 983040,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gemini-3.6-flash',
      maxContext: 1048576,
      maxTokens: 65536,
      quoteMaxToken: 983040,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gemini-3.5-flash',
      maxContext: 1048576,
      maxTokens: 65536,
      quoteMaxToken: 983040,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gemini-3.5-flash-lite',
      maxContext: 1048576,
      maxTokens: 65536,
      quoteMaxToken: 983040,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gemini-3.1-flash-lite',
      maxContext: 1048576,
      maxTokens: 65536,
      quoteMaxToken: 983040,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gemini-3.1-pro-preview',
      maxContext: 1048576,
      maxTokens: 65536,
      quoteMaxToken: 983040,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gemini-3-flash-preview',
      maxContext: 1048576,
      maxTokens: 65536,
      quoteMaxToken: 983040,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gemini-2.5-flash',
      maxContext: 1048576,
      maxTokens: 65536,
      quoteMaxToken: 983040,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gemini-2.5-pro',
      maxContext: 1048576,
      maxTokens: 65536,
      quoteMaxToken: 983040,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'gemini-2.5-flash-lite',
      maxContext: 1048576,
      maxTokens: 65536,
      quoteMaxToken: 983040,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    // xAI
    {
      type: ModelTypeEnum.llm,
      model: 'grok-4.7',
      maxContext: 500000,
      maxTokens: 500000,
      quoteMaxToken: 0,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'grok-4.5',
      maxContext: 500000,
      maxTokens: 500000,
      quoteMaxToken: 0,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'grok-4',
      maxContext: 256000,
      maxTokens: 256000,
      quoteMaxToken: 0,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'grok-3',
      maxContext: 131072,
      maxTokens: 131072,
      quoteMaxToken: 0,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    // DeepSeek
    {
      type: ModelTypeEnum.llm,
      model: 'deepseek-v4.1-flash',
      maxContext: 1000000,
      maxTokens: 384000,
      quoteMaxToken: 616000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'deepseek-v4-flash',
      maxContext: 1000000,
      maxTokens: 384000,
      quoteMaxToken: 616000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'deepseek-v4-pro',
      maxContext: 1000000,
      maxTokens: 384000,
      quoteMaxToken: 616000,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'deepseek-v3.2-exp',
      maxContext: 128000,
      maxTokens: 65536,
      quoteMaxToken: 62464,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'deepseek-r1-0528',
      maxContext: 128000,
      maxTokens: 32768,
      quoteMaxToken: 95232,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'deepseek-v3-250324',
      maxContext: 163840,
      maxTokens: 163840,
      quoteMaxToken: 0,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'deepseek-r1',
      maxContext: 128000,
      maxTokens: 32768,
      quoteMaxToken: 95232,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'deepseek-v3',
      maxContext: 131072,
      maxTokens: 8192,
      quoteMaxToken: 122880,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true,
    },
    // Moonshot
    {
      type: ModelTypeEnum.llm,
      model: 'kimi-k3',
      maxContext: 1048576,
      maxTokens: 131072,
      quoteMaxToken: 917504,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'kimi-k2.6',
      maxContext: 262144,
      maxTokens: 262144,
      quoteMaxToken: 0,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'kimi-k2-thinking',
      maxContext: 262144,
      maxTokens: 262144,
      quoteMaxToken: 0,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'kimi-k2-thinking-turbo',
      maxContext: 262144,
      maxTokens: 262144,
      quoteMaxToken: 0,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'kimi-k2.5',
      maxContext: 262144,
      maxTokens: 262144,
      quoteMaxToken: 0,
      responseFormatList: ['text'],
      vision: true,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
      showTopP: false,
      showStopSign: false,
    },
    // Zhipu
    {
      type: ModelTypeEnum.llm,
      model: 'glm-5.3',
      maxContext: 1000000,
      maxTokens: 131072,
      quoteMaxToken: 868928,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'glm-5.2',
      maxContext: 1000000,
      maxTokens: 131072,
      quoteMaxToken: 868928,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'glm-5.1',
      maxContext: 200000,
      maxTokens: 131072,
      quoteMaxToken: 68928,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'glm-5-turbo',
      maxContext: 200000,
      maxTokens: 131072,
      quoteMaxToken: 68928,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'glm-5',
      maxContext: 204800,
      maxTokens: 131072,
      quoteMaxToken: 73728,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'glm-4.7',
      maxContext: 204800,
      maxTokens: 131072,
      quoteMaxToken: 73728,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
    },
    {
      type: ModelTypeEnum.llm,
      model: 'glm-4.6',
      maxContext: 204800,
      maxTokens: 131072,
      quoteMaxToken: 73728,
      maxTemperature: 1,
      responseFormatList: ['text'],
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true,
    },
  ]
};

export default models;
