version: '3'

services:
  fastgpt-plugin:
    image: ghcr.io/labring/fastgpt-plugin:v0.0.2 # GitHub Container Registry
    # image: registry.cn-hangzhou.aliyuncs.com/labring/fastgpt-plugin:v0.0.2 # China Mainland Mirror provided by Aliyun
    # image: registry.hub.docker.com/labring/fastgpt-plugin:v0.0.2 # Docker Hub
    container_name: fastgpt-plugin
    restart: always
    networks:
      - fastgpt-plugin-network
    ports:
      - '3010:3000' # If integrated with FastGPT, you have no need to expose the port
    environment:
      - AUTH_TOKEN=FX589vMlhV # disable authentication token if you do not set this variable
      # Minio configuration
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=fastgpt-plugins
      - MINIO_USE_SSL=false
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: fastgpt-plugin-minio
    restart: always
    networks:
      - fastgpt-plugin-network
    ports: # comment out if you do not need to expose the port (in production environment, you should not expose the port)
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:

networks:
  fastgpt-plugin-network:
