# Bun 配置文件
# 详细配置说明: https://bun.sh/docs/runtime/bunfig

[install]
# 安装配置
cache = true
exact = false
production = false
optional = true
dev = true
peer = true

# 注册表配置
registry = "https://registry.npmjs.org/"

# 缓存目录
cache-dir = "~/.bun/install/cache"

[install.scopes]
# 作用域包配置
# "@myorg" = "https://registry.myorg.com/"

[test]
# 测试配置
preload = []
coverage = true

[run]
# 运行时配置
bun = true
silent = false

# 环境变量
[env]
NODE_ENV = "development"

# 开发服务器配置
[dev]
port = 3000
hot = true