import { ModelTypeEnum, type ProviderConfigType } from '../../type';

const models: ProviderConfigType = {
  provider: 'Claude',
  list: [
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 70, outputPrice: 350 }],
      model: 'claude-fable-5-1',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 200000,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 70, outputPrice: 350 }],
      model: 'claude-fable-5',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 200000,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 35, outputPrice: 175 }],
      model: 'claude-opus-4-8',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 200000,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 28, outputPrice: 140 }],
      model: 'claude-opus-5-5',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 200000,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 35, outputPrice: 175 }],
      model: 'claude-opus-5',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 200000,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 14, outputPrice: 70 }],
      model: 'claude-sonnet-5.5',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 200000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 14, outputPrice: 70 }],
      model: 'claude-sonnet-5',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 200000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 35, outputPrice: 175 }],
      model: 'claude-opus-4-7',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 200000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 21, outputPrice: 105 }],
      model: 'claude-sonnet-4-6',
      maxContext: 1000000,
      maxTokens: 64000,
      quoteMaxToken: 200000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 35, outputPrice: 175 }],
      model: 'claude-opus-4-6',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 200000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 7, outputPrice: 35 }],
      model: 'claude-haiku-4-5',
      maxContext: 200000,
      maxTokens: 64000,
      quoteMaxToken: 100000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 35, outputPrice: 175 }],
      model: 'claude-opus-4-6-20260205',
      maxContext: 1000000,
      maxTokens: 128000,
      quoteMaxToken: 200000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 21, outputPrice: 105 }],
      model: 'claude-sonnet-4-6-20260217',
      maxContext: 1000000,
      maxTokens: 64000,
      quoteMaxToken: 200000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 7, outputPrice: 35 }],
      model: 'claude-haiku-4-5-20251001',
      maxContext: 200000,
      maxTokens: 64000,
      quoteMaxToken: 100000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [
        { maxInputTokens: 200000, inputPrice: 21, outputPrice: 105 },
        { minInputTokens: 200000, inputPrice: 42, outputPrice: 157.5 }
      ],
      model: 'claude-sonnet-4-5-20250929',
      maxContext: 1000000,
      maxTokens: 64000,
      quoteMaxToken: 100000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 35, outputPrice: 175 }],
      model: 'claude-opus-4-5-20251101',
      maxContext: 200000,
      maxTokens: 64000,
      quoteMaxToken: 100000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 105, outputPrice: 525 }],
      model: 'claude-opus-4-1-20250805',
      maxContext: 200000,
      maxTokens: 32000,
      quoteMaxToken: 100000,
      maxTemperature: 1,
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true
    }
  ]
};

export default models;
