import { ModelTypeEnum, type ProviderConfigType } from '../../type';

const models: ProviderConfigType = {
  provider: 'Moonshot',
  list: [
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 21, outputPrice: 105 }],
      model: 'kimi-k3',
      maxContext: 1048576,
      maxTokens: 1048576,
      quoteMaxToken: 1000000,
      responseFormatList: ['text', 'json_object', 'json_schema'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 6.65, outputPrice: 28 }],
      model: 'kimi-k2.7-code',
      maxContext: 262144,
      maxTokens: 32768,
      quoteMaxToken: 256000,
      responseFormatList: ['text', 'json_object'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 13.3, outputPrice: 56 }],
      model: 'kimi-k2.7-code-highspeed',
      maxContext: 262144,
      maxTokens: 32768,
      quoteMaxToken: 256000,
      responseFormatList: ['text', 'json_object'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 6.65, outputPrice: 28 }],
      model: 'kimi-k2.6',
      maxContext: 262144,
      maxTokens: 32000,
      quoteMaxToken: 256000,
      responseFormatList: ['text', 'json_object'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 6.65, outputPrice: 28 }],
      model: 'kimi-k2.5',
      maxContext: 262144,
      maxTokens: 32000,
      quoteMaxToken: 256000,
      responseFormatList: ['text', 'json_object'],
      vision: true,
      reasoning: true,
      reasoningEffort: true,
      toolChoice: true,
      showTopP: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 12, outputPrice: 12 }],
      model: 'moonshot-v1-8k',
      maxContext: 8000,
      maxTokens: 4000,
      quoteMaxToken: 6000,
      maxTemperature: 1,
      responseFormatList: ['text', 'json_object'],
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 24, outputPrice: 24 }],
      model: 'moonshot-v1-32k',
      maxContext: 32000,
      maxTokens: 4000,
      quoteMaxToken: 32000,
      maxTemperature: 1,
      responseFormatList: ['text', 'json_object'],
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 60, outputPrice: 60 }],
      model: 'moonshot-v1-128k',
      maxContext: 128000,
      maxTokens: 4000,
      quoteMaxToken: 60000,
      maxTemperature: 1,
      responseFormatList: ['text', 'json_object'],
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 60, outputPrice: 60 }],
      model: 'moonshot-v1-128k-vision-preview',
      maxContext: 128000,
      maxTokens: 4000,
      quoteMaxToken: 60000,
      maxTemperature: 1,
      responseFormatList: ['text', 'json_object'],
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: true
    }
  ]
};

export default models;
