import { ModelTypeEnum, type ProviderConfigType } from '../../type';

const models: ProviderConfigType = {
  provider: 'Ernie',
  list: [
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 30, outputPrice: 90 }],
      model: 'ernie-5.1',
      maxContext: 128000,
      maxTokens: 65536,
      quoteMaxToken: 119000,
      maxTemperature: 1,
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 15, outputPrice: 60 }],
      model: 'ernie-x1.1',
      maxContext: 64000,
      maxTokens: 65536,
      quoteMaxToken: 55000,
      maxTemperature: 1,
      vision: false,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 20, outputPrice: 60 }],
      model: 'ernie-5.0',
      maxContext: 128000,
      maxTokens: 65536,
      quoteMaxToken: 119000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 20, outputPrice: 60 }],
      model: 'ernie-5.0-thinking-latest',
      maxContext: 128000,
      maxTokens: 65536,
      quoteMaxToken: 119000,
      maxTemperature: 1,
      vision: true,
      reasoning: true,
      reasoningEffort: false,
      toolChoice: true
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 3, outputPrice: 9 }],
      model: 'ernie-4.5-turbo-20260402',
      maxContext: 128000,
      maxTokens: 12288,
      quoteMaxToken: 123000,
      maxTemperature: 2,
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 3, outputPrice: 9 }],
      model: 'ernie-4.5-turbo-128k',
      maxContext: 128000,
      maxTokens: 12288,
      quoteMaxToken: 123000,
      maxTemperature: 2,
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 3, outputPrice: 9 }],
      model: 'ernie-4.5-turbo-vl',
      maxContext: 128000,
      maxTokens: 16384,
      quoteMaxToken: 123000,
      maxTemperature: 2,
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: false,
      responseFormatList: ['text', 'json_object', 'json_schema']
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 3, outputPrice: 9 }],
      model: 'ernie-4.5-turbo-32k',
      maxContext: 32000,
      maxTokens: 12288,
      quoteMaxToken: 27000,
      maxTemperature: 2,
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 3, outputPrice: 9 }],
      model: 'ernie-4.5-turbo-vl-32k',
      maxContext: 32000,
      maxTokens: 12288,
      quoteMaxToken: 27000,
      maxTemperature: 2,
      vision: true,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: false,
      responseFormatList: ['text', 'json_object', 'json_schema']
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 30, outputPrice: 90 }],
      model: 'ERNIE-4.0-8K',
      maxContext: 8000,
      maxTokens: 2048,
      quoteMaxToken: 5000,
      maxTemperature: 1,
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 8, outputPrice: 24 }],
      model: 'ERNIE-4.0-Turbo-8K',
      maxContext: 8000,
      maxTokens: 2048,
      quoteMaxToken: 5000,
      maxTemperature: 1,
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 0, outputPrice: 0 }],
      model: 'ERNIE-Lite-8K',
      maxContext: 8000,
      maxTokens: 2048,
      quoteMaxToken: 6000,
      maxTemperature: 1,
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: false
    },
    {
      type: ModelTypeEnum.llm,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 0, outputPrice: 0 }],
      model: 'ERNIE-Speed-128K',
      maxContext: 128000,
      maxTokens: 4096,
      quoteMaxToken: 120000,
      maxTemperature: 1,
      vision: false,
      reasoning: false,
      reasoningEffort: false,
      toolChoice: false
    },
    {
      type: ModelTypeEnum.embedding,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 0.5, outputPrice: 0 }],
      model: 'Embedding-V1',
      defaultToken: 512,
      maxToken: 1000,
      vision: false
    },
    {
      type: ModelTypeEnum.embedding,
      priceCurrency: 'CNY',
      billingUnit: 'tokens_per_1m',
      priceTiers: [{ inputPrice: 0.5, outputPrice: 0 }],
      model: 'tao-8k',
      defaultToken: 512,
      maxToken: 8000,
      vision: false
    }
  ]
};

export default models;
