name: Preview build image

on:
  workflow_dispatch:
  pull_request_target:
    branches: ['*']

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  pull-requests: write

jobs:
  preview-image:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            /*
            !modules/tool/packages

      # Get changed packages and test build
      - name: Get changed files in PR
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: modules/tool/packages/**

      - name: Checkout changed packages
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # Get list of changed packages
          changed_packages=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | \
            grep -oP 'modules/tool/packages/[^/]+' | \
            sort -u)

          # Checkout each changed package
          for package in $changed_packages; do
            echo "Checking out $package"
            git sparse-checkout add "$package"
          done

      - name: Setup bun
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.23
      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: bun install --frozen-lockfile && bun run install:plugins
      - name: Build pkg
        if: steps.changed-files.outputs.any_changed == 'true'
        run: bun run build:pkg

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_HUB_USERNAME }}
          password: ${{ secrets.ALI_HUB_PASSWORD }}

      - name: Build and push for amd64
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.ALI_IMAGE_NAME }}/fastgpt-plugin-pr:${{ github.event.pull_request.head.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=https://github.com/${{ github.repository }} image
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: '@finleyge/github-tools'
        uses: FinleyGe/github-tools@0.0.1
        id: print-image-label
        if: success()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tool: issue-comment
          title: Preview Image Label
          body: |
            Preview Images for this PR are:

            ```
            ${{ secrets.ALI_IMAGE_NAME }}/fastgpt-plugin-pr:${{ github.event.pull_request.head.sha }}
            ```
