name: Build image and push to registry

on:
  workflow_dispatch:
  push:
    tags: ['v*']

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        archs:
          - arch: amd64
          - arch: arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.archs.runs-on || 'ubuntu-24.04' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Login to Ali Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_HUB_USERNAME }}
          password: ${{ secrets.ALI_HUB_PASSWORD }}

      - name: Build for ${{ matrix.archs.arch }}
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/${{ matrix.archs.arch }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/fastgpt-plugin:${{ github.ref_name }}
            ${{ secrets.ALI_IMAGE_NAME }}/fastgpt-plugin:${{ github.ref_name }}
            ${{ secrets.DOCKER_IMAGE_NAME }}/fastgpt-plugin:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/fastgpt-plugin:latest
            ${{ secrets.ALI_IMAGE_NAME }}/fastgpt-plugin:latest
            ${{ secrets.DOCKER_IMAGE_NAME }}/fastgpt-plugin:latest
            ghcr.io/${{ github.repository_owner }}/fastgpt-plugin:${{ github.sha }}
            ${{ secrets.ALI_IMAGE_NAME }}/fastgpt-plugin:${{ github.sha }}
            ${{ secrets.DOCKER_IMAGE_NAME }}/fastgpt-plugin:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=https://github.com/${{ github.repository }} image
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
