name: Deploy to Marketplace

on:
  workflow_dispatch:
  push:
    # branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.23

      - name: Install root dependencies
        run: bun install --frozen-lockfile

      - name: Install tool package dependencies
        run: bun run install-all

      - name: Build and deploy to marketplace
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: bun run deploy:marketplace-data

      - name: Notify deployment success
        if: success()
        run: |
          echo "🚀 Marketplace deployment completed successfully!"
          echo "Commit: ${{ github.sha }}"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Marketplace deployment failed!"
          echo "Commit: ${{ github.sha }}"
          exit 1
